### ISSUE TITLE
Create showcase SAS code repo

### ISSUE THREAD

**Issue by WerthPADOH** [WerthPADOH/DHI-trial#9]
This project would be the flagship we can use to sell GitHub.  Ideally, it will be a generally useful collection of SAS code that people will want.

**Comment by WerthPADOH** [comment]
What should the repo have?  I think our best way to have people adopt version control is for them to use and then get involved with a repo.  Our first presentation will grab the most attention, so the example code should be useful.

I have some macros and functions that could be added, but I don't know if other people would want to use them.

Possible things to include:
- Confidence interval functions (I can't be the only one who hates copy-pasting that logic)
- Common data sets (e.g. `County`, with the 1-67 code, FIPS code, full name, and health districts)

Any other ideas?

**Comment by rwright88** [comment]
To go along with confidence interval calculations: significant difference calculations. We use different calculations depending on the size of the numerator (<100 vs. >=100 for example).

**Comment by rwright88** [comment]
I've usually calculated significant differences of counties vs. the state total.

**Comment by rwright88** [comment]
Another one I was thinking about is a function or program that calculate the counts by demographic groups, similar to EDDIE. For example, the count of births by county, sex, race, age group, etc. Let's say you wanted the count of very low birth weight births (<1500 grams) - the function could take that query as an input and output the count of very low birth weight births for all combinations of the demographic groups. This is something I do often for custom data requests.

**Comment by WerthPADOH** [comment]
Sounds like there's enough to start the repo.

@rwright88: Would you like to try creating the new repo as @PADOH-DHI?  Name's up to you.  Just add me and @Fleegal as collaborators for it, please.
